// packages/frontend/src/app/modules/form-place/components/menu/menu.component.ts
import { Component, Input, OnDestroy, OnInit } from "@angular/core";

import { AdminPlaceMenuSteps, PlaceType } from "@soliguide/common";

import { TranslateService } from "@ngx-translate/core";
import { ToastrService } from "ngx-toastr";

import { Observable, Subscription } from "rxjs";

import { AdminPlaceService } from "../../services/admin-place.service";

import { CurrentLanguageService } from "../../../general/services/current-language.service";

import { User } from "../../../users/classes";
import { AuthService } from "../../../users/services/auth.service";

import { Place } from "../../../../models/";

@Component({
  selector: "app-form-place-menu",
  templateUrl: "./menu.component.html",
  styleUrls: ["./menu.component.css"],
})
export class FormMenuPlaceComponent implements OnInit, OnDestroy {
  @Input() public place!: Place;
  @Input() public step!: AdminPlaceMenuSteps;

  private readonly subscription = new Subscription();
  public routePrefix: string;
  public placeInOrga: boolean;
  public readonly PlaceType = PlaceType;

  public currentUserSubject$: Observable<User | null>;

  constructor(
    private readonly toastr: ToastrService,
    private readonly adminPlaceService: AdminPlaceService,
    private readonly authService: AuthService,
    private readonly currentLanguageService: CurrentLanguageService,
    private readonly translateService: TranslateService
  ) {
    this.currentUserSubject$ = this.authService.currentUserSubject;
    this.placeInOrga = false;
    this.routePrefix = this.currentLanguageService.routePrefix;
  }

  public ngOnInit(): void {
    this.subscription.add(
      this.currentLanguageService.subscribe(
        () => (this.routePrefix = this.currentLanguageService.routePrefix)
      )
    );
    if (this.authService.currentUserValue.currentOrga) {
      this.placeInOrga = true;
    } else if (this.place?.lieu_id !== null) {
      this.subscription.add(
        this.adminPlaceService
          .checkInOrga(this.place.lieu_id)
          .subscribe((value: boolean) => {
            this.placeInOrga = value;
          })
      );
    }
  }

  public ngOnDestroy(): void {
    this.subscription.unsubscribe();
  }

  public infoStepNeeded() {
    this.toastr.warning(
      this.translateService.instant("MUST_COMPLETE_THIS_STEP_BEFORE_NEXT")
    );
  }
}

<!--
Soliguide: Useful information for those who need it

SPDX-FileCopyrightText: © 2024 Solinum

SPDX-License-Identifier: AGPL-3.0-only

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->
<div *ngIf="currentUserSubject$ | async as me" id="form-menu">
  <div [ngClass]="{ 'selected-item': step === 'infos' }" class="item">
    <div class="item-title">
      <span class="item-number">1</span>
      <span>
        <a
          [routerLink]="[
            routePrefix +
              '/admin-place/infos/' +
              (place.lieu_id !== null && place.lieu_id >= 0
                ? place.lieu_id
                : '')
          ]"
          routerLinkActive="router-link-active"
          >{{ "GENERAL_INFORMATION" | translate }}</a
        ></span
      >
    </div>
    <ul *ngIf="step !== 'infos'"></ul>
    <ul *ngIf="step === 'infos'">
      <li>{{ "STRUCTURE_NAME" | translate }}</li>
      <li>{{ "DESCRIPTION" | translate }}</li>
      <li>{{ "CONTACT" | translate }}</li>
    </ul>
  </div>

  <div [ngClass]="{ 'selected-item': step === 'emplacement' }" class="item">
    <div class="item-title">
      <span class="item-number">2</span>
      <span *ngIf="place.lieu_id !== null && place.stepsDone.infos">
        <a
          [routerLink]="[
            routePrefix,
            'admin-place',
            'emplacement',
            place.lieu_id
          ]"
          routerLinkActive="router-link-active"
          >{{ "LOCATION" | translate }}</a
        >
      </span>
      <span
        (click)="infoStepNeeded()"
        *ngIf="place.lieu_id === null || !place.stepsDone.infos"
        >{{ "LOCATION" | translate }}</span
      >
    </div>
    <ul *ngIf="step !== 'emplacement'"></ul>
    <ul *ngIf="step === 'emplacement'">
      <li>{{ "CHOICE" | translate }}</li>
      <ng-container *ngIf="place.placeType === PlaceType.PLACE">
        <li>{{ "COMPLETE_ADDRESS" | translate }}</li>
        <li>{{ "ADDITIONAL_ADDRESS" | translate }}</li>
      </ng-container>
      <ng-container *ngIf="place.placeType === PlaceType.ITINERARY">
        <li>{{ "WAYPOINTS" | translate }}</li>
      </ng-container>
    </ul>
  </div>

  <div
    *ngIf="placeInOrga"
    [ngClass]="{ 'selected-item': step === 'contacts' }"
    class="item"
  >
    <div class="item-title">
      <span class="item-number">3</span>
      <span *ngIf="place.lieu_id !== null && place.stepsDone.emplacement">
        <a
          [routerLink]="[routePrefix, 'admin-place', 'contacts', place.lieu_id]"
          routerLinkActive="router-link-active"
          >{{ "BUSINESS_CONTACTS" | translate }}</a
        >
      </span>
      <span
        (click)="infoStepNeeded()"
        *ngIf="place.lieu_id === null || !place.stepsDone.emplacement"
        >{{ "BUSINESS_CONTACTS" | translate }}</span
      >
    </div>
    <ul></ul>
  </div>

  <div
    *ngIf="place.placeType === PlaceType.PLACE"
    [ngClass]="{ 'selected-item': step === 'horaires' }"
    class="item"
  >
    <div class="item-title">
      <span
        *ngIf="place.placeType === PlaceType.PLACE && placeInOrga"
        class="item-number"
        >4</span
      >
      <span
        *ngIf="place.placeType === PlaceType.PLACE && !placeInOrga"
        class="item-number"
        >3</span
      >
      <span
        *ngIf="
          place.lieu_id !== null && place.stepsDone.emplacement;
          else elseHoraires
        "
      >
        <a
          [routerLink]="[routePrefix, 'admin-place', 'horaires', place.lieu_id]"
          routerLinkActive="router-link-active"
          >{{ "OPENING_HOURS" | translate }}</a
        >
      </span>
      <ng-template #elseHoraires>
        <span (click)="infoStepNeeded()">{{
          "OPENING_HOURS" | translate
        }}</span>
      </ng-template>
    </div>
    <ul></ul>
  </div>

  <div [ngClass]="{ 'selected-item': step === 'publics' }" class="item">
    <div class="item-title">
      <span
        *ngIf="place.placeType === PlaceType.PLACE && placeInOrga"
        class="item-number"
        >5</span
      >
      <span
        *ngIf="place.placeType === PlaceType.PLACE && !placeInOrga"
        class="item-number"
        >4</span
      >
      <span
        *ngIf="place.placeType === PlaceType.ITINERARY && placeInOrga"
        class="item-number"
        >3</span
      >
      <span
        *ngIf="place.placeType === PlaceType.ITINERARY && !placeInOrga"
        class="item-number"
        >2</span
      >

      <span
        *ngIf="
          place.lieu_id !== null &&
            ((place.placeType === PlaceType.PLACE &&
              place.stepsDone.horaires) ||
              (place.placeType === PlaceType.ITINERARY &&
                ((placeInOrga && place.stepsDone.contacts) ||
                  (!placeInOrga && place.stepsDone.emplacement))));
          else elsePublics
        "
      >
        <a
          [routerLink]="[routePrefix, 'admin-place', 'public', place.lieu_id]"
          routerLinkActive="router-link-active"
          >{{ "WELCOMED_PUBLIC" | translate }}</a
        >
      </span>
      <ng-template #elsePublics>
        <span (click)="infoStepNeeded()">{{
          "WELCOMED_PUBLIC" | translate
        }}</span>
      </ng-template>
    </div>
    <ul *ngIf="step !== 'publics'"></ul>
    <ul *ngIf="step === 'publics'">
      <li>{{ "PUBLIC_TYPE" | translate }}</li>
      <li>{{ "SPOKEN_LANGUAGES" | translate }}</li>
    </ul>
  </div>

  <div [ngClass]="{ 'selected-item': step === 'modalities' }" class="item">
    <div class="item-title">
      <span
        *ngIf="place.placeType === PlaceType.PLACE && placeInOrga"
        class="item-number"
        >6</span
      >
      <span
        *ngIf="place.placeType === PlaceType.PLACE && !placeInOrga"
        class="item-number"
        >5</span
      >
      <span
        *ngIf="place.placeType === PlaceType.ITINERARY && placeInOrga"
        class="item-number"
        >4</span
      >
      <span
        *ngIf="place.placeType === PlaceType.ITINERARY && !placeInOrga"
        class="item-number"
        >3</span
      >
      <span *ngIf="place.lieu_id !== null && place.stepsDone.publics">
        <a
          [routerLink]="[
            routePrefix,
            'admin-place',
            'condition',
            place.lieu_id
          ]"
          routerLinkActive="router-link-active"
          >{{ "ACCESS_CONDITIONS" | translate }}</a
        >
      </span>
      <span
        (click)="infoStepNeeded()"
        *ngIf="place.lieu_id === null || !place.stepsDone.publics"
        >{{ "ACCESS_CONDITIONS" | translate }}
      </span>
    </div>
    <ul></ul>
  </div>

  <div [ngClass]="{ 'selected-item': step === 'services' }" class="item">
    <div class="item-title">
      <span
        *ngIf="place.placeType === PlaceType.PLACE && placeInOrga"
        class="item-number"
        >7</span
      >
      <span
        *ngIf="place.placeType === PlaceType.PLACE && !placeInOrga"
        class="item-number"
        >6</span
      >
      <span
        *ngIf="place.placeType === PlaceType.ITINERARY && placeInOrga"
        class="item-number"
        >5</span
      >
      <span
        *ngIf="place.placeType === PlaceType.ITINERARY && !placeInOrga"
        class="item-number"
        >4</span
      >
      <span *ngIf="place.lieu_id !== null && place.stepsDone.conditions">
        <a
          [routerLink]="[routePrefix, 'admin-place', 'services', place.lieu_id]"
          routerLinkActive="router-link-active"
          >{{ "SERVICES_OFFERED" | translate }}</a
        >
      </span>
      <span
        (click)="infoStepNeeded()"
        *ngIf="place.lieu_id === null || !place.stepsDone.conditions"
        >{{ "SERVICES_OFFERED" | translate }}</span
      >
    </div>
    <ul></ul>
  </div>

  <div
    *ngIf="place.placeType === PlaceType.PLACE"
    [ngClass]="{ 'selected-item': step === 'photos' }"
    class="item"
  >
    <div class="item-title">
      <span *ngIf="placeInOrga" class="item-number">8</span>
      <span *ngIf="!placeInOrga" class="item-number">7</span>
      <span
        *ngIf="
          place.lieu_id !== null && place.stepsDone.services;
          else elsePhotos
        "
      >
        <a
          [routerLink]="[routePrefix, 'admin-place', 'photos', place.lieu_id]"
          routerLinkActive="router-link-active"
          >{{ "PICTURES" | translate }}</a
        >
      </span>
      <ng-template #elsePhotos>
        <span (click)="infoStepNeeded()">{{ "PICTURES" | translate }}</span>
      </ng-template>
    </div>
  </div>
</div>
<br />

<div
  *ngIf="
    place.stepsDone.infos &&
    place.stepsDone.emplacement &&
    ((placeInOrga && place.stepsDone.contacts) ||
      (!placeInOrga && !place.stepsDone.contacts)) &&
    ((place.placeType === PlaceType.PLACE && place.stepsDone.photos) ||
      (place.placeType === PlaceType.ITINERARY && !place.stepsDone.photos)) &&
    place.stepsDone.publics &&
    place.stepsDone.conditions &&
    place.stepsDone.services &&
    place.stepsDone.photos &&
    place.lieu_id !== null
  "
>
  <a
    [routerLink]="[routePrefix, 'manage-place', place.lieu_id]"
    routerLinkActive="router-link-active"
    class="btn btn-primary"
  >
    {{ "BACK_TO_PAGE" | translate }}
  </a>
</div>

// packages/design-system/src/lib/components/navigation/Menu.svelte
<!--
Soliguide: Useful information for those who need it

SPDX-FileCopyrightText: © 2024 Solinum

SPDX-License-Identifier: AGPL-3.0-only

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->
<script lang="ts">
  import type { MenuItem } from '$lib/types/Menu';
  import { createEventDispatcher } from 'svelte';
  import Badge from '../dataDisplay/Badge.svelte';
  import Text from '../Text.svelte';

  export let menuItems: MenuItem[] = [];
  export let activeItem: string;
  export let showBadge = false;

  const dispatch = createEventDispatcher();

  const handleClick = (item: MenuItem) => {
    dispatch('menuClick', {
      item: item.id
    });
  };
</script>

<nav class="menu">
  <ul role="menu">
    {#each menuItems as item}
      {@const active = item.route === activeItem}
      <li class:active aria-label={active ? item.ariaLabelActive : item.ariaLabel} role="menuitem">
        {#if active}
          <span class="menu-item">
            <span class="menu-icon active">
              <svelte:component this={item.iconActive} size="20" />
            </span>
            <Text type="caption2Medium">{item.label}</Text>
          </span>
        {:else}
          <a class="menu-item" href={item.route} on:click={() => handleClick(item)}>
            <span class="menu-icon">
              {#if item.hasBadge && showBadge}
                <span class="icon-badge"><Badge type="focus" /></span>
              {/if}
              <span class="icon-inactive"><svelte:component this={item.icon} size="20" /></span>
              <span class="icon-active"><svelte:component this={item.iconActive} size="20" /></span>
            </span>
            <Text type="caption2Medium">{item.label}</Text>
          </a>
        {/if}
      </li>
    {/each}
  </ul>
</nav>

<style lang="scss">
  nav {
    background-color: var(--color-surfaceWhite);
    height: var(--menu-height);
    box-shadow: var(--shadowXL);
  }
  ul {
    height: var(--menu-height);
    padding: var(--spacing2XS) var(--spacingLG) var(--spacingXS);
    display: flex;
    justify-content: space-between;
    align-items: center;
  }
  li {
    color: var(--color-textDark);

    .menu-item {
      min-width: 64px;
      display: flex;
      align-items: center;
      flex-direction: column;
      gap: var(--spacing4XS);
    }

    .menu-icon {
      height: 28px;
      border-radius: var(--radiusRounded);
      background-color: transparent;
      padding: 0 var(--spacingXS);
      display: flex;
      align-items: center;
      justify-content: center;
      position: relative;

      &.active {
        background-color: var(--color-surfacePrimary2);
      }
    }

    a {
      text-decoration: none;
      .icon-inactive {
        display: flex;
      }
      .icon-active {
        display: none;
      }
    }

    &:hover:not(.active),
    &:active {
      color: var(--color-textHighlightPrimary);
      a {
        .menu-icon {
          background-color: var(--color-surfaceGray3);
        }

        @media (pointer: fine) {
          .icon-inactive {
            display: none;
          }
          .icon-active {
            display: flex;
          }
        }
      }
    }

    &.active {
      color: var(--color-textHighlightPrimary);
    }
  }

  .icon-badge {
    position: absolute;
    top: -0.25rem;
    right: 0.375rem;
  }
</style>
